### ISSUE TITLE
Issue uploading code with Optiboot for Mega 2560

### ISSUE THREAD

**Issue by DavidMR91** [JAndrassy/my_boards#2]
My Arduino IDE return this error:

avrdude: Version 6.3-20190619
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf"

         Using Port                    : COM12
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
         AVR Part                      : ATmega2560
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    10     8    0 no       4096    8      0  9000  9000 0x00 0x00
           flash         65    10   256    0 yes    262144  256   1024  4500  4500 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 3
         Firmware Version: 8.0
         Vtarget         : 0.3 V
         Varef           : 0.3 V
         Oscillator      : 28.800 kHz
         SCK period      : 3.3 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9801 (probably m2560)
avrdude: reading input file "C:\Users\david\AppData\Local\Temp\arduino_build_233997/sketch_jan11a.ino.hex"
avrdude: writing flash (662 bytes):

Writing | ################################################## | 100% 0.12s

avrdude: 662 bytes of flash written
avrdude: verifying flash memory against C:\Users\david\AppData\Local\Temp\arduino_build_233997/sketch_jan11a.ino.hex:
avrdude: load data flash data from input file C:\Users\david\AppData\Local\Temp\arduino_build_233997/sketch_jan11a.ino.hex:
avrdude: input file C:\Users\david\AppData\Local\Temp\arduino_build_233997/sketch_jan11a.ino.hex contains 662 bytes
avrdude: reading on-chip flash data:

Reading | avrdude: stk500_recv(): programmer is not responding
################avrdude: stk500_recv(): programmer is not responding
avr_read(): error reading address 0x0000
    read operation not supported for memory "flash"
avrdude: failed to read all of flash memory, rc=-2
avrdude: stk500_recv(): programmer is not responding

avrdude done.  Thank you.

el puerto seleccionado 
 no existe o tu placa no esta conectada

**Comment by JAndrassy** [comment]
which Optiboot version did you 'burn'?

**Comment by DavidMR91** [comment]
I downloaded my_boards 2 days ago, and I have problems uploading "big sketchs" if i try upload an empty sketch does not fail

**Comment by JAndrassy** [comment]
> I downloaded my_boards 2 days ago, and I have problems uploading "big sketchs" if i try upload an empty sketch does not fail

you mean usb upload like in the post above? there a small sketch fails

**Comment by DavidMR91** [comment]
True, I seemed to see that correlation at one point, but it's not true, it's random.  Or at least, it fails more likely on large sketches than small ones and occasionally loads and checks correctly

**Comment by JAndrassy** [comment]
Optiboot uses higher baud rate. maybe try a different USB cable

**Comment by DavidMR91** [comment]
I have already tried 3 different cables...I have a Mega2560 board connected to an ESP12F through the Serial1 channel communicating with each other with the WifiEspAT library. I got it to work, but since a week ago I can no longer upload code to the Mega2560 (is not exact, When I receive the error reading the code in the last step of the uploading process, if I open the Serial monitor, seems that the code is right uploaded, the upload error it's maybe only in the reading check process).

I too have tested with 2 diferent PCs, with several Mega2560 boards and with several ESP12F and in all cases I get the same error in the data upload process.
I have also tried the latest version of my_boards to burn the bootloader of the board, but before it was working correctly with a minor version... (Without having updated apparently nothing started to fail with the old my_boards and that is why now I have updated and it continues to fail)

The failure is random, depending on the size of the sketch the probability of upload failure increases (I have tested it with a blank sketch and an estimated 30% of the uploads fail. With the Arduino's "blink" example the probability of failure is close to 50%, with a slightly heavier skech the failure appears in 90% of the rises)).

It also increases the probability of uploading the data correctly if we disconnect the ESP12F of the Mega2560 during the upload...

But after trying several times the code upload finally always ends up giving the upload error...

**Comment by JAndrassy** [comment]
is it a Mega with 16u2 as USB, or CH340? how is the esp-12F powered?

**Comment by DavidMR91** [comment]
Mega have CH340 and i have tested with esp-12f powered since the Mega (first, powered only using the USB and after powered Mega with an aditional power suplpy) and also tested with esp-12f powered an external power supply

**Comment by JAndrassy** [comment]
115200 baud is suboptimal for Mega and maybe the CH340 makes it worst (or 16u2 helps). 
you could try Optiboot with a different baud rate. the Mega Core has them ready. (Optiboot in Mega Core has the copy_flash_pages function for ArduinoOTA)

**Comment by DavidMR91** [comment]
Can you recommend a suitable transmission speed? And could you explain how I should change the baud rate of the USB flash?

**Comment by JAndrassy** [comment]
I looked up a the baud rate for Arduino Mega with the default bootloader.. It is 115200 too. so it can't be a problem with the baud rate. sorry

**Comment by DavidMR91** [comment]
Hello, I have found the origin of this issue, the problem is a problematic Mega 2560 PRO board assembler. Not only does it give firmware loading problems but it also has the inverted ICSP silkscreen. Seen from the photo, 5V, MOSI and GND appear on the right and are the ones on the left.
Sorry for the disturbances. I hope this report serves more people

![WhatsApp Image 2022-01-13 at 21 31 53 (1)](https://user-images.githubusercontent.com/7366359/149408395-6b6d6fe1-d3ae-4612-9dae-26d0e0426078.jpg)
